name: bluff
description: A starting point for Dart libraries or applications.
version: 0.1.9
homepage: https://github.com/aloisdeniel/bluff

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  universal_html: ^1.1.12
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
